name = "esraa-portfolio-api"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ADMIN_SECRET = "Esraa@Portfolio2025!"
FRONTEND_URL = "https://esraa-portfolio.pages.dev"

[[d1_databases]]
binding = "DB"
database_name = "esraa-portfolio-db"
database_id = "4407e473-3f5b-493a-9617-69ea9030e864"

[[kv_namespaces]]
binding = "KV"
id = "aeb5c24cc4e6496582319d48fc492ec0"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "esraa-portfolio-files"
